language: python
python:  
  - "3.8"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv install
# command to run tests
script:
  - python manage.py test
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $ACCESSKEYID
  secret_access_key:
    secure: $SECRETACCESSKEY
  region: "eu-west-2"
  app: "db2-limited"
  env: "db2-limited-dev"
  on:
    branch: dev
