# Generated by Django 3.2 on 2021-04-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_email',
            field=models.EmailField(editable=False, max_length=254),
        ),
    ]
