# Generated by Django 3.2 on 2021-04-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='author_email',
            field=models.EmailField(max_length=254),
        ),
    ]
